### ISSUE TITLE
macOS Mojave Dark Mode makes interface in light mode unusable

### ISSUE THREAD

**Issue by luksal** [psmokotnin/osm#12]
When using the system wide dark mode in macOS Mojave the interface (not using OSMs dark mode) gets unreadable:
<img width="1079" alt="macOS dark mode" src="https://user-images.githubusercontent.com/9074730/64608657-766a2380-d3cb-11e9-93b7-a9af3ef8c029.png">

**Comment by psmokotnin** [comment]
Already in work

**Comment by psmokotnin** [comment]
In the new version, you can use the application's dark mode.
![image](https://user-images.githubusercontent.com/683461/64923934-b2e0b980-d7e7-11e9-9d2d-383302d64b8c.png)

**Comment by luksal** [comment]
The Problem still exists. When using Dark mode on macOS you can't use the light mode on osm.
<img width="1659" alt="Bildschirmfoto 2020-02-27 um 23 55 01" src="https://user-images.githubusercontent.com/9074730/75494632-fa858700-59bc-11ea-9047-47d9f7336190.png">
