### ISSUE TITLE
SPL measurements

### ISSUE THREAD

**Issue by joa77** [psmokotnin/osm#19]
It would be nice to have the ability to measure SPL with various weightings (A, B, C, Z) and the possibility to integrate the SPL to get a LEQ value

**Comment by MasterLufier** [comment]
OSM use strict mathematics for measure. So weighting is phychoacoustic rules and do not have a reflex on math function.

**Comment by psmokotnin** [comment]
@joa77 it's usually asked) I've already had this in the future list

**Comment by MasterLufier** [comment]
SPL Measurement depends on measurement system calibration. First time we need to choose calibration method and then we need implement it.

**Comment by PlippiePlop** [comment]
Normally the C weighted measurement value is for high SPL measuring and it's the most used for measurements. Standard type is volt and db calibrated measurement where 2.83v/1m or 28.3v/10m. 
For measuring at 2.83v at 1 meter for subwoofers using a 60hz sin-wave where amplifier voltage output is set using RMS multimeter on the amp output on the speaker wire and db's form loudspeaker measured using db meter where its value is inserted into the measurement program calibration option. The mic is placed on the ground at noted distance from the loudspeaker cabinet (ground-plane measurement)
For tops a 1khz sin-wave is used to calibrate volts and db. This can also be ground-plane or high above the ground

for PA a more accurate measurement can be taken at 2 meters  or 10 meters 28.3 volt /db calibrated. This is for better overall distortion measuring at high output or and measuring response of multiple stacked cabinets.

for more information on measuring methods see [Data-bass measuring method description](https://data-bass.com/#/articles/5cc0bc36a75a260004255c88?_k=93xyj4) of powerful subwoofers.

**Comment by PureBasic** [comment]
A and C weighting are mendatory for any self respecting SPL measurement. They are the legal weighting here in France and you need to watch them both during a gig for public health.
The IIR coeffs are pretty easy calc. I can share my python formulas if you are interested.
There are other interesting weighting. One of the most usefull feature for musical analysis is having the possibility to slope the freq response. I usually like a +3.0 (pink) to +4.5dB/oct slope. depending on the type of music played.

**Comment by PureBasic** [comment]
Also, yeah, I use 4 inputs during a gig. 
- Two are for acoustic measurement (mic + ref), this is were I would need an SPL and weighting.
- Two are for the monitor out of the console. That way I could see the spectrum of a single channel when soloing, or see the master spectrum. This is were I would need the slope.

**Comment by psmokotnin** [comment]
> One of the most usefull feature for musical analysis is having the possibility to slope the freq response. I usually like a +3.0 (pink) to +4.5dB/oct slope. depending on the type of music played.

Describe the slope, please. Are slopping magnitude response? Maybe it should be a new issue?

**Comment by PureBasic** [comment]
Yeah this is not really related to SPL measurement, I'm opening another issue.

**Comment by sceptre0** [comment]
SPL / LEQ would be a fabulous addition to this project

**Comment by psmokotnin** [comment]
SPL and dBfs functions are implemented :)

**Comment by tionebrr** [comment]
Very nice thanks a lot!

Le lun. 19 déc. 2022 à 01:02, Pavel Smokotnin ***@***.***> a
écrit :
