### ISSUE TITLE
Overlay coherence in the magnitude view

### ISSUE THREAD

**Issue by joa77** [psmokotnin/osm#20]
For better displaying it would be nice to have the ability to overlay the coherence trace over the magnitude trace like seen in Smaart or SIM3

**Comment by psmokotnin** [comment]
I don't think that copy another software is a good practice. I prefer to see all data with its colors than only one selected.

**Comment by joa77** [comment]
I understand this. Then I would be nice to have 4 views to view Impulse Response, Phase, Magnitude and coherence at once.
(or maybe five, so that you can include the RTA too)
