### ISSUE TITLE
Use fixed PPO for frequency resolution

### ISSUE THREAD

**Issue by joa77** [psmokotnin/osm#21]
To achieve better performance on the graphs and better readability it would be very great to have a fixed amount of points per octave.
Details for implementation can be found here: https://www.merlijnvanveen.nl/en/study-hall/162-time-records-part-i

**Comment by psmokotnin** [comment]
already in the TODO list

**Comment by psmokotnin** [comment]
Done. Will be include in future update.

**Comment by psmokotnin** [comment]
included in  v0.3
