### ISSUE TITLE
ASIO Support?

### ISSUE THREAD

**Issue by Marcus-evjen** [psmokotnin/osm#24]
Hi I did a little testing of the program and it looks very promising.
One problem I have is that I use a focurite sound card, which I can't use to take measurements. Every time i try i get a message telling me that "Device is not supported."
Usually in other software it is possible to choose ASIO, and further the sound card itself. I was wondring could be an option in software in the future. 
Because this looks very promising from what I can see!

**Comment by psmokotnin** [comment]
ASIO is already on the ToDo list.

**Comment by PlippiePlop** [comment]
Well at least an option to select which input/output to use.
For any measurement program it's a basic requirement.
