### ISSUE TITLE
Can't dowload SetupOSM.exe

### ISSUE THREAD

**Issue by crisbek** [psmokotnin/osm#29]
Click on link and next page is
![image](https://user-images.githubusercontent.com/62272421/76817096-b24dcd80-67e0-11ea-8457-6ec09e08d8e2.png)

**Comment by psmokotnin** [comment]
Looks like you had a problem with an internet connection. All files are located at Github's servers. Be sure, that Github and Amazon are not blocked in your country.
Please, try again. If it won't work, try to use a VPN.
