### ISSUE TITLE
About measurement stored and export

### ISSUE THREAD

**Issue by Clark-Chan** [psmokotnin/osm#32]
OSM is so cool! 
I almost do everything with it this often,and enjoy that.

I have tried to store a measurement and save as a .frd file.
When I import this .frd file to FIR Creator,phase curve was invert.
But it isn’t invert in the phase window of measurement.
And I open the .frd file to read data,phase data was also invert.
How could I make some adjustment

**Comment by psmokotnin** [comment]
I'll check it once again. Thanks

**Comment by Clark-Chan** [comment]
Спасибо

**Comment by psmokotnin** [comment]
fixed
