### ISSUE TITLE
[ENHANCEMENT] FFT buffer size expressed as N rather than an exponent

### ISSUE THREAD

**Issue by PureBasic** [psmokotnin/osm#36]
Most analyzer I have found express the buffer length as samples (1024, 2048, ... 8192 etc). It might be a good idea to express the buffer length the same way in OSM to avoid confusion and stay within the industry standard.

**Comment by psmokotnin** [comment]
Numbers like 65536 says nothing to users and only confuse. 
Let's change the standard. UI has to be simple.
