### ISSUE TITLE
erro: parou de funcionar

### ISSUE THREAD

**Issue by luizcarloscosta** [psmokotnin/osm#39]
Ao iniciar o programa, apare a mensagem : "Parou de funcionar" as vezes funciona por um tempo e lógo a pare ce amensagem novamente e fecha. Esse bug está presente no Win7 e Win10.

**Comment by psmokotnin** [comment]
Please, describe in the details (and English) your error message and what do you do before it.

**Comment by luizcarloscosta** [comment]
Hello I hope you understand what I'm writing
i'm brazilian and i don't speak english.

When opening OpensoundMeter, a window appears with the message: Opensoundmeter has stopped working. A problem caused the program to stop working properly. Windows will close the program and notify you if a solution is available.

**Comment by psmokotnin** [comment]
@luizcarloscosta try to select another default audio input device in Windows.
