### ISSUE TITLE
App doesn't open and crashes on MacOS

### ISSUE THREAD

**Issue by andrebahiense** [psmokotnin/osm#40]
After months without using the Mac version of the program, the application does not start, the window closes automatically after less than a second and no error message appears. I even tried some of the older versions, but the same thing happens. I'm using a MacBook Pro with Mojave 10.14.6.

**Comment by psmokotnin** [comment]
@andrebahienseChange your default input device. There was a bug: crash when used some of RME or same devices.
This bug is already fixed in future release.
