### ISSUE TITLE
DVS compatibilty

### ISSUE THREAD

**Issue by Mathias666** [psmokotnin/osm#43]
Hi
I tried yesterday to use DVS (Dante Virtual Soundcard) with OSM.
OSM didn't recognise DVS…
Is there any issue with DVS ?

Thanx

**Comment by psmokotnin** [comment]
@Mathias666 what is your OS?

**Comment by Mathias666** [comment]
Hi
Win 10 family (all updates done)
DVS: lastest version

**Comment by psmokotnin** [comment]
@Mathias666 Did you try to use WDM driver of DVS? Note, ASIO drivers are not supported now.

**Comment by Mathias666** [comment]
Oops!
OK, I'm understanding now. I used ASIO driver, next time I'll use WDM (or my Macbook Pro…) 😉
Thank you very much
