### ISSUE TITLE
All Graphs Blank Except RTA and Spectrogram

### ISSUE THREAD

**Issue by lukasubo** [psmokotnin/osm#46]
Hi,

I'm sure I'm doing something wrong, but I've been trying this program and I can't seem to get any measurements to graph except for the RTA and Spectrogram. Any idea where I might be going wrong?

Thanks

![image](https://user-images.githubusercontent.com/5761515/115977139-2c539880-a543-11eb-9c24-1a1ebbb34f10.png)

**Comment by psmokotnin** [comment]
@lukasubo You have no signal at the reference channel. All charts except RTA and Spectrograph represent relation between two channels.
