### ISSUE TITLE
Visual Studio 2019/2022?

### ISSUE THREAD

**Issue by snarkipus** [psmokotnin/osm#50]
Anyone successful in getting this to import/build in Visual Studio 2019/2022?

Note:
Builds fine using Qt Creator and Qt environment - opening the *.pro in Visual Studio 2019/2022 using Qt Visual Studio Tools Extension seems to die a horrible death.

**Comment by psmokotnin** [comment]
I used Qt tools for VS and it worked good.
Now I use Qt Creator with MSVC

**Comment by snarkipus** [comment]
Thanks - unfortunately Qt Creator doesn't have any profiling tools that work on Windows (besides QML) so I was hoping to get a working build in VS. Do you have a working soln file?
