### ISSUE TITLE
Impulse Filter 

### ISSUE THREAD

**Issue by FLORIANSV35** [psmokotnin/osm#52]
Hi.
It will be great to add impulse frequency filter.
Thanks !

**Comment by psmokotnin** [comment]
@FLORIANSV35 explain in the details, please.

**Comment by melimat** [comment]
@FLORIANSV35 do you mean adding feature similar to Smaart, where you can adjust settings of delay finder, where you can set the filter frequency in order to improve delay finder performace on subwoofers?

**Comment by maximeborges** [comment]
I would assume that he was talking about a FIR filter. It is commonly used for room correction for example, you get your measurements, generate a FIR impulse with rephase for example, and apply that to your system.
Having the ability to apply an FIR impulse on a measurement would allow to check in real time if the current tuning makes sense or would require some modification, without additional hardware in the loop.

**Comment by psmokotnin** [comment]
@maximeborges there is already everything to apply the imported FIR filter on a measurement. You can do it with a combination of Windowing and Math (Apply mode) sources.

Since, there is no info from @FLORIANSV35, I'm closing this issue
