### ISSUE TITLE
Can't get it to work on Ubuntu 22.04

### ISSUE THREAD

**Issue by fhackenberger** [psmokotnin/osm#53]
I've downloaded the AppImage and can run it. I need to use _pasuspender_ to allow it to see my sound card (I can not select the device in the measurement properties), but I still don't see anything in the measurement chart. Am I overlooking something? There's nothing relevant in the log.txt file either.

**Comment by ariendj** [comment]
Same problem here, I cannot select a recording interface or a output device. Where do I set up my sound card?

**Comment by psmokotnin** [comment]
On Linux Audio works through the ALSA driver. Check, that you have it.

**Comment by JredG** [comment]
Using Ubuntu 20.04, I have glibc installed, essentials installed, and the appimage will not run citing missing glibc_2.29.

**Comment by psmokotnin** [comment]
@JredG What is your version? For 20.04 6_2.31 is available.

**Comment by JredG** [comment]
I have upgraded to 20, and it will now run! I really haven't got to do a
big test yet, but was able to navigate and experiment. Great project!! I
was missing a dependency somewhere. I almost built, but decided to do the
upgrade anyway. Thanks

**Comment by psmokotnin** [comment]
That's good :)
