### ISSUE TITLE
Feature to save chart sets

### ISSUE THREAD

**Issue by datadata95** [psmokotnin/osm#54]
It could come handy to be able to save sets of different charts, and be able to recall them with shortcuts.

I'm thinking for example one with impulse, magnitude and and phase for example when tuning the system, and then another set during performance with for example spl meter, rta and spectrogram. You could be able to store and recall whatever charts you'd like and then recall them for different purposes.

**Comment by psmokotnin** [comment]
Yes, it's a good idea. We have something like this in our todo list :)
