### ISSUE TITLE
Add Support for long term loudness average measurements 

### ISSUE THREAD

**Issue by 12xx12** [psmokotnin/osm#61]
To complete the audio toolkit an option to average the loudness measured over a longer time interval [1, 5, 15, 30, 60, infinite] minutes might be interesting.

**Comment by NexAdn** [comment]
I propose a few additions to this:

* allow setting a target loudness value (LUFS), similar to the target trace (more a nice-to-have than a priority)
* show integrated loudness, true peak and loudness range according to EBU R-128

This would make the tool very handy and informative for monitoring loudness in live broadcasts.

**Comment by psmokotnin** [comment]
Open Sound Meter is more for live sound and I have a lot of functions to implement. Its future is more in acoustics than in broadcasting. So, Leq is already in todo list.
Measurement for EBU standard is even another type of measurement and requires another approach and achitecture.

**Comment by josh-barker** [comment]
Hey @psmokotnin , just wondering when the Leq feature might be coming?

Thanks!

**Comment by psmokotnin** [comment]
@josh-barker Since it's a very important tool, I hope in the next months.

**Comment by psmokotnin** [comment]
Done. Will be included in future v1.3

**Comment by 12xx12** [comment]
Thanks !!!!
