### ISSUE TITLE
Adjustable audio device sample rate

### ISSUE THREAD

**Issue by Holzus** [psmokotnin/osm#64]
Maybe I could not find it, but there seems to be no possibility to change the sampling rate of the audio device in use. I checked the latest 1.2.2 Release.

**Comment by psmokotnin** [comment]
Device's sample rate can always be changed in its settings or in application provided by the manufacture. There is no real reason to include this setting in the application. Even more, such setting can become a reason for unpredicted sample-rate conversion in the chain.
