### ISSUE TITLE
Remember Dark Mode

### ISSUE THREAD

**Issue by Holzus** [psmokotnin/osm#65]
Just a minor thing: Would be great, if the Dark Mode setting persists. I have tested V1 2.2 on Win10 and 11. One needs to activate it after every program launch.

**Comment by theantnest** [comment]
Nope, I'm on Win 11, system theme is dark mode. Dark mode does not persist for me either.

**Comment by psmokotnin** [comment]
I'll check it out. By default, software follows system mode because UI sometimes is useless if modes don't match.

**Comment by psmokotnin** [comment]
In v1.3(soon) saving the application's settings was changed. Now it works stable. Dark mode and other settings was tested on Windows and work good.
