### ISSUE TITLE
Windows 11 crashing

### ISSUE THREAD

**Issue by ccgsavhelpdesktech** [psmokotnin/osm#66]
Hi 

I've been playing around with Open Sound Meter v1.2.2 on a Windows 11 fully updated machine but when I selected the magnitude graph it instantly crashed and now just crashes when I open the program. I'm using DVS as the audio interface but even with dvs stopped its still crashing I've also uninstalled and reinstalled, tried v1.2.1 as well. I have also tried deleting the data in appdata/local/opensoundmeter but to no avail. it seems like there is still some config somewhere I can't clear. Any ideas?

**Comment by leocb** [comment]
Also crashing for me
Interface: Roland Duo Capture EX
Win 11 22H2
First install (as of today) from the website

**Comment by psmokotnin** [comment]
Please, clear all the records for OpenSoundMeter in the Windows register.

PS This bug is already in work and will be fixes in future release

**Comment by psmokotnin** [comment]
Fix will be included in v1.3.

**Comment by v-Lildeer** [comment]
Same issue now in 1.3 version :/
Windows 11 (last updates)
Interface: Esi Ugm192

**Comment by psmokotnin** [comment]
@v-Lildeer
cleaning the application's folder will help. Fix is comming
