### ISSUE TITLE
Won't start on macOS Mojave

### ISSUE THREAD

**Issue by luksal** [psmokotnin/osm#7]
The first time i tried osm it started normally and worked perfekt. But now every time i try to start it, it will only keep bouncing in the dock forever

**Comment by psmokotnin** [comment]
Check if your default audio device support 48K. If not, select another audio device as default in os.

**Comment by psmokotnin** [comment]
Sample rate fix has been included to the next update already.

**Comment by luksal** [comment]
Even with setting the samplerate to 48k osm won't start

**Comment by psmokotnin** [comment]
What audio interface do you use?

**Comment by luksal** [comment]
Roland Octa Capture
Soundflower 2 & 64
Macbook BuildIn Audiointerface
