### ISSUE TITLE
Remote API Documentation

### ISSUE THREAD

**Issue by elianterelle** [psmokotnin/osm#71]
is there any documentation for the remote api?
I'd like to write a little script to graph spl values. I'm not sure if the remote api is the best way to do this, as i don't know if it sends out the metrics like spl and levels or if that is calculated in the client when using osm on two devices connected via the api.
Maybe you can point me in the right direction...

**Comment by psmokotnin** [comment]
For the moment, there is no documentation for the API. We are planning to publish it.
It is JSON format that includes all the data, and everything is calculated in the software (server instance).
