### ISSUE TITLE
Applying a low pass filter to a stored measurement isn't resulting in the expected filtering

### ISSUE THREAD

**Issue by ross** [psmokotnin/osm#72]
I have a completely raw/default measurement of a single sub (with OK coherence all above .7 in case that's relevant)

<img width="977" alt="Screen Shot 2023-08-28 at 7 24 51 PM" src="https://github.com/psmokotnin/osm/assets/12789/ea4a3b1f-97a4-43e2-92a0-f1440e221998">

and a 10th order Butterworth LP filter at 100Hz.

<img width="644" alt="Screen Shot 2023-08-28 at 7 25 12 PM" src="https://github.com/psmokotnin/osm/assets/12789/26e07023-9c7b-4d3e-84fc-62107a9bae0b">

I then created a math source and set it to Apply with the stored measurement and the lp filter:

<img width="1552" alt="Screen Shot 2023-08-28 at 7 27 23 PM" src="https://github.com/psmokotnin/osm/assets/12789/83294540-7faf-416e-857e-44a8f4f44568">

I expected the math source to preserve the sub measurement below 100Hz and quickly attenuate the signal above it, but as you can see in the image above it has no effect until 357Hz.

To check my approach I switched to a high pass filter @ 100Hz and quickly generated a signal and measurement with my laptop. I get the expected behavior in this case where the measurement has some signal below 100Hz, but when the high pass filter is applied to it that response is attenuated roughly in line with the filter's fall off. 

<img width="1552" alt="Screen Shot 2023-08-28 at 7 31 27 PM" src="https://github.com/psmokotnin/osm/assets/12789/b468b2a8-9be1-4542-9601-28e1ab4000f7">

Anyway, not sure if my setup and/or expectations are wrong. 

I've enjoyed playing around with the software over the past couple days or so and have managed to hand tune my home system fairly well with it as I've been experimenting. I was looking to model various cross over points and I would like to play around with seeing if I could code up the ability to simulate the effects of PEQ, I guess similar to https://github.com/psmokotnin/osm/issues/69. 

Regardless thanks for all the work you've put into OSM.

**Comment by ross** [comment]
Figured out what was up. The measurement was taken at 192kHz and the low pass filter was set to 48kHz.

When I change the LP filter to 192kHz

<img width="655" alt="Screen Shot 2023-08-29 at 12 51 25 PM" src="https://github.com/psmokotnin/osm/assets/12789/cb5a2dbb-c467-4b09-aa4f-f9e36239f32a">

I guess I assumed that since it forces the same transform mode that it was also forcing the same sample rate to be used so I didn't check to see what the rate of the measurement was once the math apply started displaying data.

With the sample rate matched I get the expected behavior:

<img width="1804" alt="Screen Shot 2023-08-29 at 12 54 12 PM" src="https://github.com/psmokotnin/osm/assets/12789/5cc86adc-96e8-4577-ae33-95c766be8911">

I'll go ahead and leave this open in case the same rate mis-match should be an error the same way that source size is. Feel free to close if not.

**Comment by psmokotnin** [comment]
I am glad you figured out why there was an issue.
I'll add to my task list a new task to check all the sources have a common sample rate.
