### ISSUE TITLE
[Feature] Leq / LAeq SPL Measurements

### ISSUE THREAD

**Issue by jjeising** [psmokotnin/osm#74]
Integrated measurements are much relevant today e.g. for audience protection. It would be great to implemented an Leq measurement with variable weighting (LAeq, LCeq) and variable time (e.g. 1 minute, 5 minutes, 30 minutes are very common). A continuous measurement/reset would also be help to track Leq of complete show.

**Comment by psmokotnin** [comment]
Leq meters with time 1', 5', 15', 30' and 60' for all curves added
