### ISSUE TITLE
Polar diff slightly off?

### ISSUE THREAD

**Issue by simonjohansson** [psmokotnin/osm#84]
Hello! I don't really know what Im doing, Im just trying to align my sub. Presumably Im missing something, but just in case Ive stumbled across a bug.

I would expect the diff to be 0 where the two phases cross, but as you can see from the screenshot it's around 10 degrees.

<img width="1352" alt="Screenshot 2023-11-21 at 23 48 23" src="https://github.com/psmokotnin/osm/assets/736248/2ed29b5e-2041-48c8-9ee2-1f1d9b4a0ad2">

If I diff the sub/speakers with itself the line is static at 0 degrees.

Running 1.3

Thanks!

**Comment by psmokotnin** [comment]
that happens due to the spectral average in the charts.
