### ISSUE TITLE
Fast delete with Ctrl

### ISSUE THREAD

**Issue by manuelliebchen** [psmokotnin/osm#85]
Often when I work with osm I set up 4 microphones and an average for measuring a sound system.

For measuring I activate the generator, reset the buffer and save the traces with Ctrl+X so I can have the full over view without needing the generator anymore. 
Afterwards I adjust the sound system and do the same again. 

This leads to a very clutter trace list very fast so I often delete all the traces from past measurements. Now this is somewhat annoying because I have to click delete and then navigate to the popup and press okey. 

My suggestion would be that by pressing "Ctrl" and clicking the delete button the popup does not show up so one could delete multiple traces quite fast. Alternatively it could be possible to confirm the popup with the enter key so one has not to move the mouse.

I would be happy to implement it myselfe if you would accept the Issue.

**Comment by psmokotnin** [comment]
You can swipe a source to the left to quickly delete it or to the right to temporarily hide it from the list.
