### ISSUE TITLE
I can't get it to display a graph or play a sound

### ISSUE THREAD

**Issue by iopq** [psmokotnin/osm#87]
the software is doing nothing and I have no idea what I'm doing wrong

I installed from NixOS version: 1.3

![Screenshot from 2024-03-28 15-59-54](https://github.com/psmokotnin/osm/assets/1817528/e44d3e02-479c-45f6-aaa9-a73844bb1419)

**Comment by psmokotnin** [comment]
You need to check your system, audio drivers and routing.

**Comment by iopq** [comment]
It's fine, I was able to get REW to work by simply selecting the correct sound source

![Screenshot from 2024-03-28 22-25-54](https://github.com/psmokotnin/osm/assets/1817528/3288abb7-2052-4c11-9691-70b122fd3abd)

there's no sound source selection in OSM

**Comment by iopq** [comment]
running from command line gives

```
audio device not present  "plughw:0,3"
```

**Comment by MagicRB** [comment]
@psmokotnin this is an issue on your end. Youre using alsa as the audio plugin, which you should not. You should be using pipewire/pulseaudio instead for maximum compatibility
